image:
- Visual Studio 2022
environment:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
before_build:
- pwsh: |
    Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
    ./dotnet-install.ps1 -JSonFile global.json -Architecture x64 -InstallDir 'C:\Program Files\dotnet'
    dotnet tool restore --tool-manifest src/.config/dotnet-tools.json
build_script:
- dotnet build --configuration Release
- dotnet test --configuration Release --no-build --no-restore
test: off
artifacts:
- path: nugets\*.nupkg